# Generated by Django 3.1 on 2020-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200904_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title_short',
            field=models.CharField(default=1, max_length=200, verbose_name='Заголовок, при наведении курсора'),
            preserve_default=False,
        ),
    ]
