# Generated by Django 3.1 on 2020-09-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_title_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('number',)},
        ),
    ]
