# Generated by Django 3.1 on 2020-09-09 16:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200909_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(default='', verbose_name='Подробное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(default='', verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
