# Generated by Django 3.1 on 2020-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20200909_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
